services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped
  streamlit:
    image: bankierubybank/ai-frontend:latest
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit-ai-frontend
    ports:
      - 8080:8501
    environment:
      - OLLAMA_HOST=ollama
volumes:
  ollama: {}
  open-webui: {}
