name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: SonarQube Scan
      #   uses: SonarSource/sonarqube-scan-action@v5.2.0
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # - name: Aqua Security Trivy
      #   uses: aquasecurity/trivy-action@0.29.0
      #   with:
      #     scan-type: fs
      #     scan-ref: "."
      #     scanners: vuln,secret,misconfig,license # optional, default is vuln,secret
      #   continue-on-error: true
  build:
    needs: pre-build
    # Ref: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-latest
    steps:
      - name: Set image tag
        id: set-image-tag
        run: echo "IMAGE_TAG=$([[ ${{ github.ref }} == 'refs/heads/main' ]] && echo '${{ github.run_number }}' || echo 'dev')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build ./app --file ./app/Dockerfile --tag bankierubybank/bkrbybk-ailab:${{ env.IMAGE_TAG }}
      # - name: Aqua Security Trivy
      #   uses: aquasecurity/trivy-action@0.29.0
      #   with:
      #     scan-type: image
      #     image-ref: "bankierubybank/microsvc-dd:${{ env.IMAGE_TAG }}"
      #     ignore-unfixed: true # optional, default is false
      #     severity: HIGH,CRITICAL # optional, default is UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      #   continue-on-error: true
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: bankierubybank
      #     password: ${{ secrets.DOCKER_HUB_PAT }}
      # - name: Push image to registry (Docker Hub)
      #   run: |
      #     docker push bankierubybank/bkrbybk-ailab:${{ env.IMAGE_TAG }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-7
      - name: Amazon ECR "Login" Action for GitHub Actions
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.7.4
        with:
          task-definition: .aws/task-definition.json
          container-name: bankierubybank/bkrbybk-ailab
          image: bankierubybank/bkrbybk-ailab:dev
      - name: Amazon ECS "Deploy Task Definition" Action for GitHub Actions
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.3.3
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ailab-frontend
          cluster: demo-ecs
          wait-for-service-stability: true
